/********************************************************************************
** Form generated from reading UI file 'SudokuUI.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SUDOKUUI_H
#define UI_SUDOKUUI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_SudokuUIClass
{
public:
    QWidget *centralWidget;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_9;
    QFrame *line;
    QFrame *line_2;
    QLineEdit *lineEdit_10;
    QLineEdit *lineEdit_11;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_18;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QLineEdit *lineEdit_21;
    QLineEdit *lineEdit_22;
    QLineEdit *lineEdit_23;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QLineEdit *lineEdit_26;
    QLineEdit *lineEdit_27;
    QLineEdit *lineEdit_28;
    QLineEdit *lineEdit_29;
    QLineEdit *lineEdit_30;
    QLineEdit *lineEdit_31;
    QLineEdit *lineEdit_32;
    QLineEdit *lineEdit_33;
    QLineEdit *lineEdit_34;
    QLineEdit *lineEdit_35;
    QLineEdit *lineEdit_36;
    QLineEdit *lineEdit_37;
    QLineEdit *lineEdit_38;
    QLineEdit *lineEdit_39;
    QLineEdit *lineEdit_40;
    QLineEdit *lineEdit_41;
    QLineEdit *lineEdit_42;
    QLineEdit *lineEdit_43;
    QLineEdit *lineEdit_44;
    QLineEdit *lineEdit_45;
    QLineEdit *lineEdit_46;
    QLineEdit *lineEdit_47;
    QLineEdit *lineEdit_48;
    QLineEdit *lineEdit_49;
    QLineEdit *lineEdit_50;
    QLineEdit *lineEdit_51;
    QLineEdit *lineEdit_52;
    QLineEdit *lineEdit_53;
    QLineEdit *lineEdit_54;
    QLineEdit *lineEdit_55;
    QLineEdit *lineEdit_56;
    QLineEdit *lineEdit_57;
    QLineEdit *lineEdit_58;
    QLineEdit *lineEdit_59;
    QLineEdit *lineEdit_60;
    QLineEdit *lineEdit_61;
    QLineEdit *lineEdit_62;
    QLineEdit *lineEdit_63;
    QLineEdit *lineEdit_64;
    QLineEdit *lineEdit_65;
    QLineEdit *lineEdit_66;
    QLineEdit *lineEdit_67;
    QLineEdit *lineEdit_68;
    QLineEdit *lineEdit_69;
    QLineEdit *lineEdit_70;
    QLineEdit *lineEdit_71;
    QLineEdit *lineEdit_72;
    QLineEdit *lineEdit_73;
    QLineEdit *lineEdit_74;
    QLineEdit *lineEdit_75;
    QLineEdit *lineEdit_76;
    QLineEdit *lineEdit_77;
    QLineEdit *lineEdit_78;
    QLineEdit *lineEdit_79;
    QLineEdit *lineEdit_80;
    QLineEdit *lineEdit_81;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QLCDNumber *LCDCurTimeCost;
    QLineEdit *curTimecost;
    QLineEdit *minTimeCost;
    QLCDNumber *LCDMinTimeCost;
    QPushButton *preGame;
    QPushButton *nextGame;
    QPushButton *pushButton_6;
    QPushButton *pushButton_4;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *SudokuUIClass)
    {
        if (SudokuUIClass->objectName().isEmpty())
            SudokuUIClass->setObjectName(QStringLiteral("SudokuUIClass"));
        SudokuUIClass->resize(649, 554);
        centralWidget = new QWidget(SudokuUIClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        lineEdit = new QLineEdit(centralWidget);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(50, 50, 40, 40));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(lineEdit->sizePolicy().hasHeightForWidth());
        lineEdit->setSizePolicy(sizePolicy);
        lineEdit->setMinimumSize(QSize(40, 40));
        lineEdit->setMaximumSize(QSize(40, 40));
        QFont font;
        font.setFamily(QStringLiteral("Arial"));
        font.setPointSize(18);
        font.setBold(true);
        font.setWeight(75);
        lineEdit->setFont(font);
        lineEdit->setAlignment(Qt::AlignCenter);
        lineEdit_2 = new QLineEdit(centralWidget);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(90, 50, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_2->sizePolicy().hasHeightForWidth());
        lineEdit_2->setSizePolicy(sizePolicy);
        lineEdit_2->setMinimumSize(QSize(40, 40));
        lineEdit_2->setMaximumSize(QSize(40, 40));
        lineEdit_2->setFont(font);
        lineEdit_2->setAlignment(Qt::AlignCenter);
        lineEdit_3 = new QLineEdit(centralWidget);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(130, 50, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_3->sizePolicy().hasHeightForWidth());
        lineEdit_3->setSizePolicy(sizePolicy);
        lineEdit_3->setMinimumSize(QSize(40, 40));
        lineEdit_3->setMaximumSize(QSize(40, 40));
        lineEdit_3->setFont(font);
        lineEdit_3->setAlignment(Qt::AlignCenter);
        lineEdit_4 = new QLineEdit(centralWidget);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(50, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_4->sizePolicy().hasHeightForWidth());
        lineEdit_4->setSizePolicy(sizePolicy);
        lineEdit_4->setMinimumSize(QSize(40, 40));
        lineEdit_4->setMaximumSize(QSize(40, 40));
        lineEdit_4->setFont(font);
        lineEdit_4->setAlignment(Qt::AlignCenter);
        lineEdit_5 = new QLineEdit(centralWidget);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(130, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_5->sizePolicy().hasHeightForWidth());
        lineEdit_5->setSizePolicy(sizePolicy);
        lineEdit_5->setMinimumSize(QSize(40, 40));
        lineEdit_5->setMaximumSize(QSize(40, 40));
        lineEdit_5->setFont(font);
        lineEdit_5->setAlignment(Qt::AlignCenter);
        lineEdit_6 = new QLineEdit(centralWidget);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(90, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_6->sizePolicy().hasHeightForWidth());
        lineEdit_6->setSizePolicy(sizePolicy);
        lineEdit_6->setMinimumSize(QSize(40, 40));
        lineEdit_6->setMaximumSize(QSize(40, 40));
        lineEdit_6->setFont(font);
        lineEdit_6->setAlignment(Qt::AlignCenter);
        lineEdit_7 = new QLineEdit(centralWidget);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(50, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_7->sizePolicy().hasHeightForWidth());
        lineEdit_7->setSizePolicy(sizePolicy);
        lineEdit_7->setMinimumSize(QSize(40, 40));
        lineEdit_7->setMaximumSize(QSize(40, 40));
        lineEdit_7->setFont(font);
        lineEdit_7->setAlignment(Qt::AlignCenter);
        lineEdit_8 = new QLineEdit(centralWidget);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(130, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_8->sizePolicy().hasHeightForWidth());
        lineEdit_8->setSizePolicy(sizePolicy);
        lineEdit_8->setMinimumSize(QSize(40, 40));
        lineEdit_8->setMaximumSize(QSize(40, 40));
        lineEdit_8->setFont(font);
        lineEdit_8->setAlignment(Qt::AlignCenter);
        lineEdit_9 = new QLineEdit(centralWidget);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(90, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_9->sizePolicy().hasHeightForWidth());
        lineEdit_9->setSizePolicy(sizePolicy);
        lineEdit_9->setMinimumSize(QSize(40, 40));
        lineEdit_9->setMaximumSize(QSize(40, 40));
        lineEdit_9->setFont(font);
        lineEdit_9->setAlignment(Qt::AlignCenter);
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(50, 170, 360, 5));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(170, 50, 5, 360));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        lineEdit_10 = new QLineEdit(centralWidget);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(170, 50, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_10->sizePolicy().hasHeightForWidth());
        lineEdit_10->setSizePolicy(sizePolicy);
        lineEdit_10->setMinimumSize(QSize(40, 40));
        lineEdit_10->setMaximumSize(QSize(40, 40));
        lineEdit_10->setFont(font);
        lineEdit_10->setAlignment(Qt::AlignCenter);
        lineEdit_11 = new QLineEdit(centralWidget);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(170, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_11->sizePolicy().hasHeightForWidth());
        lineEdit_11->setSizePolicy(sizePolicy);
        lineEdit_11->setMinimumSize(QSize(40, 40));
        lineEdit_11->setMaximumSize(QSize(40, 40));
        lineEdit_11->setFont(font);
        lineEdit_11->setAlignment(Qt::AlignCenter);
        lineEdit_12 = new QLineEdit(centralWidget);
        lineEdit_12->setObjectName(QStringLiteral("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(210, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_12->sizePolicy().hasHeightForWidth());
        lineEdit_12->setSizePolicy(sizePolicy);
        lineEdit_12->setMinimumSize(QSize(40, 40));
        lineEdit_12->setMaximumSize(QSize(40, 40));
        lineEdit_12->setFont(font);
        lineEdit_12->setAlignment(Qt::AlignCenter);
        lineEdit_13 = new QLineEdit(centralWidget);
        lineEdit_13->setObjectName(QStringLiteral("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(210, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_13->sizePolicy().hasHeightForWidth());
        lineEdit_13->setSizePolicy(sizePolicy);
        lineEdit_13->setMinimumSize(QSize(40, 40));
        lineEdit_13->setMaximumSize(QSize(40, 40));
        lineEdit_13->setFont(font);
        lineEdit_13->setAlignment(Qt::AlignCenter);
        lineEdit_14 = new QLineEdit(centralWidget);
        lineEdit_14->setObjectName(QStringLiteral("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(250, 50, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_14->sizePolicy().hasHeightForWidth());
        lineEdit_14->setSizePolicy(sizePolicy);
        lineEdit_14->setMinimumSize(QSize(40, 40));
        lineEdit_14->setMaximumSize(QSize(40, 40));
        lineEdit_14->setFont(font);
        lineEdit_14->setAlignment(Qt::AlignCenter);
        lineEdit_15 = new QLineEdit(centralWidget);
        lineEdit_15->setObjectName(QStringLiteral("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(170, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_15->sizePolicy().hasHeightForWidth());
        lineEdit_15->setSizePolicy(sizePolicy);
        lineEdit_15->setMinimumSize(QSize(40, 40));
        lineEdit_15->setMaximumSize(QSize(40, 40));
        lineEdit_15->setFont(font);
        lineEdit_15->setAlignment(Qt::AlignCenter);
        lineEdit_16 = new QLineEdit(centralWidget);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(250, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_16->sizePolicy().hasHeightForWidth());
        lineEdit_16->setSizePolicy(sizePolicy);
        lineEdit_16->setMinimumSize(QSize(40, 40));
        lineEdit_16->setMaximumSize(QSize(40, 40));
        lineEdit_16->setFont(font);
        lineEdit_16->setAlignment(Qt::AlignCenter);
        lineEdit_17 = new QLineEdit(centralWidget);
        lineEdit_17->setObjectName(QStringLiteral("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(250, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_17->sizePolicy().hasHeightForWidth());
        lineEdit_17->setSizePolicy(sizePolicy);
        lineEdit_17->setMinimumSize(QSize(40, 40));
        lineEdit_17->setMaximumSize(QSize(40, 40));
        lineEdit_17->setFont(font);
        lineEdit_17->setAlignment(Qt::AlignCenter);
        lineEdit_18 = new QLineEdit(centralWidget);
        lineEdit_18->setObjectName(QStringLiteral("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(210, 50, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_18->sizePolicy().hasHeightForWidth());
        lineEdit_18->setSizePolicy(sizePolicy);
        lineEdit_18->setMinimumSize(QSize(40, 40));
        lineEdit_18->setMaximumSize(QSize(40, 40));
        lineEdit_18->setFont(font);
        lineEdit_18->setAlignment(Qt::AlignCenter);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(290, 50, 5, 360));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(50, 50, 5, 360));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(410, 50, 5, 360));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(50, 50, 360, 5));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(50, 290, 360, 5));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(50, 410, 360, 5));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        lineEdit_19 = new QLineEdit(centralWidget);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(50, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_19->sizePolicy().hasHeightForWidth());
        lineEdit_19->setSizePolicy(sizePolicy);
        lineEdit_19->setMinimumSize(QSize(40, 40));
        lineEdit_19->setMaximumSize(QSize(40, 40));
        lineEdit_19->setFont(font);
        lineEdit_19->setAlignment(Qt::AlignCenter);
        lineEdit_20 = new QLineEdit(centralWidget);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(90, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_20->sizePolicy().hasHeightForWidth());
        lineEdit_20->setSizePolicy(sizePolicy);
        lineEdit_20->setMinimumSize(QSize(40, 40));
        lineEdit_20->setMaximumSize(QSize(40, 40));
        lineEdit_20->setFont(font);
        lineEdit_20->setAlignment(Qt::AlignCenter);
        lineEdit_21 = new QLineEdit(centralWidget);
        lineEdit_21->setObjectName(QStringLiteral("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(50, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_21->sizePolicy().hasHeightForWidth());
        lineEdit_21->setSizePolicy(sizePolicy);
        lineEdit_21->setMinimumSize(QSize(40, 40));
        lineEdit_21->setMaximumSize(QSize(40, 40));
        lineEdit_21->setFont(font);
        lineEdit_21->setAlignment(Qt::AlignCenter);
        lineEdit_22 = new QLineEdit(centralWidget);
        lineEdit_22->setObjectName(QStringLiteral("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(130, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_22->sizePolicy().hasHeightForWidth());
        lineEdit_22->setSizePolicy(sizePolicy);
        lineEdit_22->setMinimumSize(QSize(40, 40));
        lineEdit_22->setMaximumSize(QSize(40, 40));
        lineEdit_22->setFont(font);
        lineEdit_22->setAlignment(Qt::AlignCenter);
        lineEdit_23 = new QLineEdit(centralWidget);
        lineEdit_23->setObjectName(QStringLiteral("lineEdit_23"));
        lineEdit_23->setGeometry(QRect(90, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_23->sizePolicy().hasHeightForWidth());
        lineEdit_23->setSizePolicy(sizePolicy);
        lineEdit_23->setMinimumSize(QSize(40, 40));
        lineEdit_23->setMaximumSize(QSize(40, 40));
        lineEdit_23->setFont(font);
        lineEdit_23->setAlignment(Qt::AlignCenter);
        lineEdit_24 = new QLineEdit(centralWidget);
        lineEdit_24->setObjectName(QStringLiteral("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(50, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_24->sizePolicy().hasHeightForWidth());
        lineEdit_24->setSizePolicy(sizePolicy);
        lineEdit_24->setMinimumSize(QSize(40, 40));
        lineEdit_24->setMaximumSize(QSize(40, 40));
        lineEdit_24->setFont(font);
        lineEdit_24->setAlignment(Qt::AlignCenter);
        lineEdit_25 = new QLineEdit(centralWidget);
        lineEdit_25->setObjectName(QStringLiteral("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(130, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_25->sizePolicy().hasHeightForWidth());
        lineEdit_25->setSizePolicy(sizePolicy);
        lineEdit_25->setMinimumSize(QSize(40, 40));
        lineEdit_25->setMaximumSize(QSize(40, 40));
        lineEdit_25->setFont(font);
        lineEdit_25->setAlignment(Qt::AlignCenter);
        lineEdit_26 = new QLineEdit(centralWidget);
        lineEdit_26->setObjectName(QStringLiteral("lineEdit_26"));
        lineEdit_26->setGeometry(QRect(130, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_26->sizePolicy().hasHeightForWidth());
        lineEdit_26->setSizePolicy(sizePolicy);
        lineEdit_26->setMinimumSize(QSize(40, 40));
        lineEdit_26->setMaximumSize(QSize(40, 40));
        lineEdit_26->setFont(font);
        lineEdit_26->setAlignment(Qt::AlignCenter);
        lineEdit_27 = new QLineEdit(centralWidget);
        lineEdit_27->setObjectName(QStringLiteral("lineEdit_27"));
        lineEdit_27->setGeometry(QRect(90, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_27->sizePolicy().hasHeightForWidth());
        lineEdit_27->setSizePolicy(sizePolicy);
        lineEdit_27->setMinimumSize(QSize(40, 40));
        lineEdit_27->setMaximumSize(QSize(40, 40));
        lineEdit_27->setFont(font);
        lineEdit_27->setAlignment(Qt::AlignCenter);
        lineEdit_28 = new QLineEdit(centralWidget);
        lineEdit_28->setObjectName(QStringLiteral("lineEdit_28"));
        lineEdit_28->setGeometry(QRect(290, 50, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_28->sizePolicy().hasHeightForWidth());
        lineEdit_28->setSizePolicy(sizePolicy);
        lineEdit_28->setMinimumSize(QSize(40, 40));
        lineEdit_28->setMaximumSize(QSize(40, 40));
        lineEdit_28->setFont(font);
        lineEdit_28->setAlignment(Qt::AlignCenter);
        lineEdit_29 = new QLineEdit(centralWidget);
        lineEdit_29->setObjectName(QStringLiteral("lineEdit_29"));
        lineEdit_29->setGeometry(QRect(330, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_29->sizePolicy().hasHeightForWidth());
        lineEdit_29->setSizePolicy(sizePolicy);
        lineEdit_29->setMinimumSize(QSize(40, 40));
        lineEdit_29->setMaximumSize(QSize(40, 40));
        lineEdit_29->setFont(font);
        lineEdit_29->setAlignment(Qt::AlignCenter);
        lineEdit_30 = new QLineEdit(centralWidget);
        lineEdit_30->setObjectName(QStringLiteral("lineEdit_30"));
        lineEdit_30->setGeometry(QRect(290, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_30->sizePolicy().hasHeightForWidth());
        lineEdit_30->setSizePolicy(sizePolicy);
        lineEdit_30->setMinimumSize(QSize(40, 40));
        lineEdit_30->setMaximumSize(QSize(40, 40));
        lineEdit_30->setFont(font);
        lineEdit_30->setAlignment(Qt::AlignCenter);
        lineEdit_31 = new QLineEdit(centralWidget);
        lineEdit_31->setObjectName(QStringLiteral("lineEdit_31"));
        lineEdit_31->setGeometry(QRect(370, 50, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_31->sizePolicy().hasHeightForWidth());
        lineEdit_31->setSizePolicy(sizePolicy);
        lineEdit_31->setMinimumSize(QSize(40, 40));
        lineEdit_31->setMaximumSize(QSize(40, 40));
        lineEdit_31->setFont(font);
        lineEdit_31->setAlignment(Qt::AlignCenter);
        lineEdit_32 = new QLineEdit(centralWidget);
        lineEdit_32->setObjectName(QStringLiteral("lineEdit_32"));
        lineEdit_32->setGeometry(QRect(330, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_32->sizePolicy().hasHeightForWidth());
        lineEdit_32->setSizePolicy(sizePolicy);
        lineEdit_32->setMinimumSize(QSize(40, 40));
        lineEdit_32->setMaximumSize(QSize(40, 40));
        lineEdit_32->setFont(font);
        lineEdit_32->setAlignment(Qt::AlignCenter);
        lineEdit_33 = new QLineEdit(centralWidget);
        lineEdit_33->setObjectName(QStringLiteral("lineEdit_33"));
        lineEdit_33->setGeometry(QRect(290, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_33->sizePolicy().hasHeightForWidth());
        lineEdit_33->setSizePolicy(sizePolicy);
        lineEdit_33->setMinimumSize(QSize(40, 40));
        lineEdit_33->setMaximumSize(QSize(40, 40));
        lineEdit_33->setFont(font);
        lineEdit_33->setAlignment(Qt::AlignCenter);
        lineEdit_34 = new QLineEdit(centralWidget);
        lineEdit_34->setObjectName(QStringLiteral("lineEdit_34"));
        lineEdit_34->setGeometry(QRect(370, 90, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_34->sizePolicy().hasHeightForWidth());
        lineEdit_34->setSizePolicy(sizePolicy);
        lineEdit_34->setMinimumSize(QSize(40, 40));
        lineEdit_34->setMaximumSize(QSize(40, 40));
        lineEdit_34->setFont(font);
        lineEdit_34->setAlignment(Qt::AlignCenter);
        lineEdit_35 = new QLineEdit(centralWidget);
        lineEdit_35->setObjectName(QStringLiteral("lineEdit_35"));
        lineEdit_35->setGeometry(QRect(370, 130, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_35->sizePolicy().hasHeightForWidth());
        lineEdit_35->setSizePolicy(sizePolicy);
        lineEdit_35->setMinimumSize(QSize(40, 40));
        lineEdit_35->setMaximumSize(QSize(40, 40));
        lineEdit_35->setFont(font);
        lineEdit_35->setAlignment(Qt::AlignCenter);
        lineEdit_36 = new QLineEdit(centralWidget);
        lineEdit_36->setObjectName(QStringLiteral("lineEdit_36"));
        lineEdit_36->setGeometry(QRect(330, 50, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_36->sizePolicy().hasHeightForWidth());
        lineEdit_36->setSizePolicy(sizePolicy);
        lineEdit_36->setMinimumSize(QSize(40, 40));
        lineEdit_36->setMaximumSize(QSize(40, 40));
        lineEdit_36->setFont(font);
        lineEdit_36->setAlignment(Qt::AlignCenter);
        lineEdit_37 = new QLineEdit(centralWidget);
        lineEdit_37->setObjectName(QStringLiteral("lineEdit_37"));
        lineEdit_37->setGeometry(QRect(170, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_37->sizePolicy().hasHeightForWidth());
        lineEdit_37->setSizePolicy(sizePolicy);
        lineEdit_37->setMinimumSize(QSize(40, 40));
        lineEdit_37->setMaximumSize(QSize(40, 40));
        lineEdit_37->setFont(font);
        lineEdit_37->setAlignment(Qt::AlignCenter);
        lineEdit_38 = new QLineEdit(centralWidget);
        lineEdit_38->setObjectName(QStringLiteral("lineEdit_38"));
        lineEdit_38->setGeometry(QRect(210, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_38->sizePolicy().hasHeightForWidth());
        lineEdit_38->setSizePolicy(sizePolicy);
        lineEdit_38->setMinimumSize(QSize(40, 40));
        lineEdit_38->setMaximumSize(QSize(40, 40));
        lineEdit_38->setFont(font);
        lineEdit_38->setAlignment(Qt::AlignCenter);
        lineEdit_39 = new QLineEdit(centralWidget);
        lineEdit_39->setObjectName(QStringLiteral("lineEdit_39"));
        lineEdit_39->setGeometry(QRect(170, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_39->sizePolicy().hasHeightForWidth());
        lineEdit_39->setSizePolicy(sizePolicy);
        lineEdit_39->setMinimumSize(QSize(40, 40));
        lineEdit_39->setMaximumSize(QSize(40, 40));
        lineEdit_39->setFont(font);
        lineEdit_39->setAlignment(Qt::AlignCenter);
        lineEdit_40 = new QLineEdit(centralWidget);
        lineEdit_40->setObjectName(QStringLiteral("lineEdit_40"));
        lineEdit_40->setGeometry(QRect(250, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_40->sizePolicy().hasHeightForWidth());
        lineEdit_40->setSizePolicy(sizePolicy);
        lineEdit_40->setMinimumSize(QSize(40, 40));
        lineEdit_40->setMaximumSize(QSize(40, 40));
        lineEdit_40->setFont(font);
        lineEdit_40->setAlignment(Qt::AlignCenter);
        lineEdit_41 = new QLineEdit(centralWidget);
        lineEdit_41->setObjectName(QStringLiteral("lineEdit_41"));
        lineEdit_41->setGeometry(QRect(210, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_41->sizePolicy().hasHeightForWidth());
        lineEdit_41->setSizePolicy(sizePolicy);
        lineEdit_41->setMinimumSize(QSize(40, 40));
        lineEdit_41->setMaximumSize(QSize(40, 40));
        lineEdit_41->setFont(font);
        lineEdit_41->setAlignment(Qt::AlignCenter);
        lineEdit_42 = new QLineEdit(centralWidget);
        lineEdit_42->setObjectName(QStringLiteral("lineEdit_42"));
        lineEdit_42->setGeometry(QRect(170, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_42->sizePolicy().hasHeightForWidth());
        lineEdit_42->setSizePolicy(sizePolicy);
        lineEdit_42->setMinimumSize(QSize(40, 40));
        lineEdit_42->setMaximumSize(QSize(40, 40));
        lineEdit_42->setFont(font);
        lineEdit_42->setAlignment(Qt::AlignCenter);
        lineEdit_43 = new QLineEdit(centralWidget);
        lineEdit_43->setObjectName(QStringLiteral("lineEdit_43"));
        lineEdit_43->setGeometry(QRect(250, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_43->sizePolicy().hasHeightForWidth());
        lineEdit_43->setSizePolicy(sizePolicy);
        lineEdit_43->setMinimumSize(QSize(40, 40));
        lineEdit_43->setMaximumSize(QSize(40, 40));
        lineEdit_43->setFont(font);
        lineEdit_43->setAlignment(Qt::AlignCenter);
        lineEdit_44 = new QLineEdit(centralWidget);
        lineEdit_44->setObjectName(QStringLiteral("lineEdit_44"));
        lineEdit_44->setGeometry(QRect(250, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_44->sizePolicy().hasHeightForWidth());
        lineEdit_44->setSizePolicy(sizePolicy);
        lineEdit_44->setMinimumSize(QSize(40, 40));
        lineEdit_44->setMaximumSize(QSize(40, 40));
        lineEdit_44->setFont(font);
        lineEdit_44->setAlignment(Qt::AlignCenter);
        lineEdit_45 = new QLineEdit(centralWidget);
        lineEdit_45->setObjectName(QStringLiteral("lineEdit_45"));
        lineEdit_45->setGeometry(QRect(210, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_45->sizePolicy().hasHeightForWidth());
        lineEdit_45->setSizePolicy(sizePolicy);
        lineEdit_45->setMinimumSize(QSize(40, 40));
        lineEdit_45->setMaximumSize(QSize(40, 40));
        lineEdit_45->setFont(font);
        lineEdit_45->setAlignment(Qt::AlignCenter);
        lineEdit_46 = new QLineEdit(centralWidget);
        lineEdit_46->setObjectName(QStringLiteral("lineEdit_46"));
        lineEdit_46->setGeometry(QRect(290, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_46->sizePolicy().hasHeightForWidth());
        lineEdit_46->setSizePolicy(sizePolicy);
        lineEdit_46->setMinimumSize(QSize(40, 40));
        lineEdit_46->setMaximumSize(QSize(40, 40));
        lineEdit_46->setFont(font);
        lineEdit_46->setAlignment(Qt::AlignCenter);
        lineEdit_47 = new QLineEdit(centralWidget);
        lineEdit_47->setObjectName(QStringLiteral("lineEdit_47"));
        lineEdit_47->setGeometry(QRect(330, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_47->sizePolicy().hasHeightForWidth());
        lineEdit_47->setSizePolicy(sizePolicy);
        lineEdit_47->setMinimumSize(QSize(40, 40));
        lineEdit_47->setMaximumSize(QSize(40, 40));
        lineEdit_47->setFont(font);
        lineEdit_47->setAlignment(Qt::AlignCenter);
        lineEdit_48 = new QLineEdit(centralWidget);
        lineEdit_48->setObjectName(QStringLiteral("lineEdit_48"));
        lineEdit_48->setGeometry(QRect(290, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_48->sizePolicy().hasHeightForWidth());
        lineEdit_48->setSizePolicy(sizePolicy);
        lineEdit_48->setMinimumSize(QSize(40, 40));
        lineEdit_48->setMaximumSize(QSize(40, 40));
        lineEdit_48->setFont(font);
        lineEdit_48->setAlignment(Qt::AlignCenter);
        lineEdit_49 = new QLineEdit(centralWidget);
        lineEdit_49->setObjectName(QStringLiteral("lineEdit_49"));
        lineEdit_49->setGeometry(QRect(370, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_49->sizePolicy().hasHeightForWidth());
        lineEdit_49->setSizePolicy(sizePolicy);
        lineEdit_49->setMinimumSize(QSize(40, 40));
        lineEdit_49->setMaximumSize(QSize(40, 40));
        lineEdit_49->setFont(font);
        lineEdit_49->setAlignment(Qt::AlignCenter);
        lineEdit_50 = new QLineEdit(centralWidget);
        lineEdit_50->setObjectName(QStringLiteral("lineEdit_50"));
        lineEdit_50->setGeometry(QRect(330, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_50->sizePolicy().hasHeightForWidth());
        lineEdit_50->setSizePolicy(sizePolicy);
        lineEdit_50->setMinimumSize(QSize(40, 40));
        lineEdit_50->setMaximumSize(QSize(40, 40));
        lineEdit_50->setFont(font);
        lineEdit_50->setAlignment(Qt::AlignCenter);
        lineEdit_51 = new QLineEdit(centralWidget);
        lineEdit_51->setObjectName(QStringLiteral("lineEdit_51"));
        lineEdit_51->setGeometry(QRect(290, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_51->sizePolicy().hasHeightForWidth());
        lineEdit_51->setSizePolicy(sizePolicy);
        lineEdit_51->setMinimumSize(QSize(40, 40));
        lineEdit_51->setMaximumSize(QSize(40, 40));
        lineEdit_51->setFont(font);
        lineEdit_51->setAlignment(Qt::AlignCenter);
        lineEdit_52 = new QLineEdit(centralWidget);
        lineEdit_52->setObjectName(QStringLiteral("lineEdit_52"));
        lineEdit_52->setGeometry(QRect(370, 210, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_52->sizePolicy().hasHeightForWidth());
        lineEdit_52->setSizePolicy(sizePolicy);
        lineEdit_52->setMinimumSize(QSize(40, 40));
        lineEdit_52->setMaximumSize(QSize(40, 40));
        lineEdit_52->setFont(font);
        lineEdit_52->setAlignment(Qt::AlignCenter);
        lineEdit_53 = new QLineEdit(centralWidget);
        lineEdit_53->setObjectName(QStringLiteral("lineEdit_53"));
        lineEdit_53->setGeometry(QRect(370, 250, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_53->sizePolicy().hasHeightForWidth());
        lineEdit_53->setSizePolicy(sizePolicy);
        lineEdit_53->setMinimumSize(QSize(40, 40));
        lineEdit_53->setMaximumSize(QSize(40, 40));
        lineEdit_53->setFont(font);
        lineEdit_53->setAlignment(Qt::AlignCenter);
        lineEdit_54 = new QLineEdit(centralWidget);
        lineEdit_54->setObjectName(QStringLiteral("lineEdit_54"));
        lineEdit_54->setGeometry(QRect(330, 170, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_54->sizePolicy().hasHeightForWidth());
        lineEdit_54->setSizePolicy(sizePolicy);
        lineEdit_54->setMinimumSize(QSize(40, 40));
        lineEdit_54->setMaximumSize(QSize(40, 40));
        lineEdit_54->setFont(font);
        lineEdit_54->setAlignment(Qt::AlignCenter);
        lineEdit_55 = new QLineEdit(centralWidget);
        lineEdit_55->setObjectName(QStringLiteral("lineEdit_55"));
        lineEdit_55->setGeometry(QRect(50, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_55->sizePolicy().hasHeightForWidth());
        lineEdit_55->setSizePolicy(sizePolicy);
        lineEdit_55->setMinimumSize(QSize(40, 40));
        lineEdit_55->setMaximumSize(QSize(40, 40));
        lineEdit_55->setFont(font);
        lineEdit_55->setAlignment(Qt::AlignCenter);
        lineEdit_56 = new QLineEdit(centralWidget);
        lineEdit_56->setObjectName(QStringLiteral("lineEdit_56"));
        lineEdit_56->setGeometry(QRect(90, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_56->sizePolicy().hasHeightForWidth());
        lineEdit_56->setSizePolicy(sizePolicy);
        lineEdit_56->setMinimumSize(QSize(40, 40));
        lineEdit_56->setMaximumSize(QSize(40, 40));
        lineEdit_56->setFont(font);
        lineEdit_56->setAlignment(Qt::AlignCenter);
        lineEdit_57 = new QLineEdit(centralWidget);
        lineEdit_57->setObjectName(QStringLiteral("lineEdit_57"));
        lineEdit_57->setGeometry(QRect(50, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_57->sizePolicy().hasHeightForWidth());
        lineEdit_57->setSizePolicy(sizePolicy);
        lineEdit_57->setMinimumSize(QSize(40, 40));
        lineEdit_57->setMaximumSize(QSize(40, 40));
        lineEdit_57->setFont(font);
        lineEdit_57->setAlignment(Qt::AlignCenter);
        lineEdit_58 = new QLineEdit(centralWidget);
        lineEdit_58->setObjectName(QStringLiteral("lineEdit_58"));
        lineEdit_58->setGeometry(QRect(130, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_58->sizePolicy().hasHeightForWidth());
        lineEdit_58->setSizePolicy(sizePolicy);
        lineEdit_58->setMinimumSize(QSize(40, 40));
        lineEdit_58->setMaximumSize(QSize(40, 40));
        lineEdit_58->setFont(font);
        lineEdit_58->setAlignment(Qt::AlignCenter);
        lineEdit_59 = new QLineEdit(centralWidget);
        lineEdit_59->setObjectName(QStringLiteral("lineEdit_59"));
        lineEdit_59->setGeometry(QRect(90, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_59->sizePolicy().hasHeightForWidth());
        lineEdit_59->setSizePolicy(sizePolicy);
        lineEdit_59->setMinimumSize(QSize(40, 40));
        lineEdit_59->setMaximumSize(QSize(40, 40));
        lineEdit_59->setFont(font);
        lineEdit_59->setAlignment(Qt::AlignCenter);
        lineEdit_60 = new QLineEdit(centralWidget);
        lineEdit_60->setObjectName(QStringLiteral("lineEdit_60"));
        lineEdit_60->setGeometry(QRect(50, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_60->sizePolicy().hasHeightForWidth());
        lineEdit_60->setSizePolicy(sizePolicy);
        lineEdit_60->setMinimumSize(QSize(40, 40));
        lineEdit_60->setMaximumSize(QSize(40, 40));
        lineEdit_60->setFont(font);
        lineEdit_60->setAlignment(Qt::AlignCenter);
        lineEdit_61 = new QLineEdit(centralWidget);
        lineEdit_61->setObjectName(QStringLiteral("lineEdit_61"));
        lineEdit_61->setGeometry(QRect(130, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_61->sizePolicy().hasHeightForWidth());
        lineEdit_61->setSizePolicy(sizePolicy);
        lineEdit_61->setMinimumSize(QSize(40, 40));
        lineEdit_61->setMaximumSize(QSize(40, 40));
        lineEdit_61->setFont(font);
        lineEdit_61->setAlignment(Qt::AlignCenter);
        lineEdit_62 = new QLineEdit(centralWidget);
        lineEdit_62->setObjectName(QStringLiteral("lineEdit_62"));
        lineEdit_62->setGeometry(QRect(130, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_62->sizePolicy().hasHeightForWidth());
        lineEdit_62->setSizePolicy(sizePolicy);
        lineEdit_62->setMinimumSize(QSize(40, 40));
        lineEdit_62->setMaximumSize(QSize(40, 40));
        lineEdit_62->setFont(font);
        lineEdit_62->setAlignment(Qt::AlignCenter);
        lineEdit_63 = new QLineEdit(centralWidget);
        lineEdit_63->setObjectName(QStringLiteral("lineEdit_63"));
        lineEdit_63->setGeometry(QRect(90, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_63->sizePolicy().hasHeightForWidth());
        lineEdit_63->setSizePolicy(sizePolicy);
        lineEdit_63->setMinimumSize(QSize(40, 40));
        lineEdit_63->setMaximumSize(QSize(40, 40));
        lineEdit_63->setFont(font);
        lineEdit_63->setAlignment(Qt::AlignCenter);
        lineEdit_64 = new QLineEdit(centralWidget);
        lineEdit_64->setObjectName(QStringLiteral("lineEdit_64"));
        lineEdit_64->setGeometry(QRect(170, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_64->sizePolicy().hasHeightForWidth());
        lineEdit_64->setSizePolicy(sizePolicy);
        lineEdit_64->setMinimumSize(QSize(40, 40));
        lineEdit_64->setMaximumSize(QSize(40, 40));
        lineEdit_64->setFont(font);
        lineEdit_64->setAlignment(Qt::AlignCenter);
        lineEdit_65 = new QLineEdit(centralWidget);
        lineEdit_65->setObjectName(QStringLiteral("lineEdit_65"));
        lineEdit_65->setGeometry(QRect(210, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_65->sizePolicy().hasHeightForWidth());
        lineEdit_65->setSizePolicy(sizePolicy);
        lineEdit_65->setMinimumSize(QSize(40, 40));
        lineEdit_65->setMaximumSize(QSize(40, 40));
        lineEdit_65->setFont(font);
        lineEdit_65->setAlignment(Qt::AlignCenter);
        lineEdit_66 = new QLineEdit(centralWidget);
        lineEdit_66->setObjectName(QStringLiteral("lineEdit_66"));
        lineEdit_66->setGeometry(QRect(170, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_66->sizePolicy().hasHeightForWidth());
        lineEdit_66->setSizePolicy(sizePolicy);
        lineEdit_66->setMinimumSize(QSize(40, 40));
        lineEdit_66->setMaximumSize(QSize(40, 40));
        lineEdit_66->setFont(font);
        lineEdit_66->setAlignment(Qt::AlignCenter);
        lineEdit_67 = new QLineEdit(centralWidget);
        lineEdit_67->setObjectName(QStringLiteral("lineEdit_67"));
        lineEdit_67->setGeometry(QRect(250, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_67->sizePolicy().hasHeightForWidth());
        lineEdit_67->setSizePolicy(sizePolicy);
        lineEdit_67->setMinimumSize(QSize(40, 40));
        lineEdit_67->setMaximumSize(QSize(40, 40));
        lineEdit_67->setFont(font);
        lineEdit_67->setAlignment(Qt::AlignCenter);
        lineEdit_68 = new QLineEdit(centralWidget);
        lineEdit_68->setObjectName(QStringLiteral("lineEdit_68"));
        lineEdit_68->setGeometry(QRect(210, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_68->sizePolicy().hasHeightForWidth());
        lineEdit_68->setSizePolicy(sizePolicy);
        lineEdit_68->setMinimumSize(QSize(40, 40));
        lineEdit_68->setMaximumSize(QSize(40, 40));
        lineEdit_68->setFont(font);
        lineEdit_68->setAlignment(Qt::AlignCenter);
        lineEdit_69 = new QLineEdit(centralWidget);
        lineEdit_69->setObjectName(QStringLiteral("lineEdit_69"));
        lineEdit_69->setGeometry(QRect(170, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_69->sizePolicy().hasHeightForWidth());
        lineEdit_69->setSizePolicy(sizePolicy);
        lineEdit_69->setMinimumSize(QSize(40, 40));
        lineEdit_69->setMaximumSize(QSize(40, 40));
        lineEdit_69->setFont(font);
        lineEdit_69->setAlignment(Qt::AlignCenter);
        lineEdit_70 = new QLineEdit(centralWidget);
        lineEdit_70->setObjectName(QStringLiteral("lineEdit_70"));
        lineEdit_70->setGeometry(QRect(250, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_70->sizePolicy().hasHeightForWidth());
        lineEdit_70->setSizePolicy(sizePolicy);
        lineEdit_70->setMinimumSize(QSize(40, 40));
        lineEdit_70->setMaximumSize(QSize(40, 40));
        lineEdit_70->setFont(font);
        lineEdit_70->setAlignment(Qt::AlignCenter);
        lineEdit_71 = new QLineEdit(centralWidget);
        lineEdit_71->setObjectName(QStringLiteral("lineEdit_71"));
        lineEdit_71->setGeometry(QRect(250, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_71->sizePolicy().hasHeightForWidth());
        lineEdit_71->setSizePolicy(sizePolicy);
        lineEdit_71->setMinimumSize(QSize(40, 40));
        lineEdit_71->setMaximumSize(QSize(40, 40));
        lineEdit_71->setFont(font);
        lineEdit_71->setAlignment(Qt::AlignCenter);
        lineEdit_72 = new QLineEdit(centralWidget);
        lineEdit_72->setObjectName(QStringLiteral("lineEdit_72"));
        lineEdit_72->setGeometry(QRect(210, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_72->sizePolicy().hasHeightForWidth());
        lineEdit_72->setSizePolicy(sizePolicy);
        lineEdit_72->setMinimumSize(QSize(40, 40));
        lineEdit_72->setMaximumSize(QSize(40, 40));
        lineEdit_72->setFont(font);
        lineEdit_72->setAlignment(Qt::AlignCenter);
        lineEdit_73 = new QLineEdit(centralWidget);
        lineEdit_73->setObjectName(QStringLiteral("lineEdit_73"));
        lineEdit_73->setGeometry(QRect(290, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_73->sizePolicy().hasHeightForWidth());
        lineEdit_73->setSizePolicy(sizePolicy);
        lineEdit_73->setMinimumSize(QSize(40, 40));
        lineEdit_73->setMaximumSize(QSize(40, 40));
        lineEdit_73->setFont(font);
        lineEdit_73->setAlignment(Qt::AlignCenter);
        lineEdit_74 = new QLineEdit(centralWidget);
        lineEdit_74->setObjectName(QStringLiteral("lineEdit_74"));
        lineEdit_74->setGeometry(QRect(330, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_74->sizePolicy().hasHeightForWidth());
        lineEdit_74->setSizePolicy(sizePolicy);
        lineEdit_74->setMinimumSize(QSize(40, 40));
        lineEdit_74->setMaximumSize(QSize(40, 40));
        lineEdit_74->setFont(font);
        lineEdit_74->setAlignment(Qt::AlignCenter);
        lineEdit_75 = new QLineEdit(centralWidget);
        lineEdit_75->setObjectName(QStringLiteral("lineEdit_75"));
        lineEdit_75->setGeometry(QRect(290, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_75->sizePolicy().hasHeightForWidth());
        lineEdit_75->setSizePolicy(sizePolicy);
        lineEdit_75->setMinimumSize(QSize(40, 40));
        lineEdit_75->setMaximumSize(QSize(40, 40));
        lineEdit_75->setFont(font);
        lineEdit_75->setAlignment(Qt::AlignCenter);
        lineEdit_76 = new QLineEdit(centralWidget);
        lineEdit_76->setObjectName(QStringLiteral("lineEdit_76"));
        lineEdit_76->setGeometry(QRect(370, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_76->sizePolicy().hasHeightForWidth());
        lineEdit_76->setSizePolicy(sizePolicy);
        lineEdit_76->setMinimumSize(QSize(40, 40));
        lineEdit_76->setMaximumSize(QSize(40, 40));
        lineEdit_76->setFont(font);
        lineEdit_76->setAlignment(Qt::AlignCenter);
        lineEdit_77 = new QLineEdit(centralWidget);
        lineEdit_77->setObjectName(QStringLiteral("lineEdit_77"));
        lineEdit_77->setGeometry(QRect(330, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_77->sizePolicy().hasHeightForWidth());
        lineEdit_77->setSizePolicy(sizePolicy);
        lineEdit_77->setMinimumSize(QSize(40, 40));
        lineEdit_77->setMaximumSize(QSize(40, 40));
        lineEdit_77->setFont(font);
        lineEdit_77->setAlignment(Qt::AlignCenter);
        lineEdit_78 = new QLineEdit(centralWidget);
        lineEdit_78->setObjectName(QStringLiteral("lineEdit_78"));
        lineEdit_78->setGeometry(QRect(290, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_78->sizePolicy().hasHeightForWidth());
        lineEdit_78->setSizePolicy(sizePolicy);
        lineEdit_78->setMinimumSize(QSize(40, 40));
        lineEdit_78->setMaximumSize(QSize(40, 40));
        lineEdit_78->setFont(font);
        lineEdit_78->setAlignment(Qt::AlignCenter);
        lineEdit_79 = new QLineEdit(centralWidget);
        lineEdit_79->setObjectName(QStringLiteral("lineEdit_79"));
        lineEdit_79->setGeometry(QRect(370, 330, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_79->sizePolicy().hasHeightForWidth());
        lineEdit_79->setSizePolicy(sizePolicy);
        lineEdit_79->setMinimumSize(QSize(40, 40));
        lineEdit_79->setMaximumSize(QSize(40, 40));
        lineEdit_79->setFont(font);
        lineEdit_79->setAlignment(Qt::AlignCenter);
        lineEdit_80 = new QLineEdit(centralWidget);
        lineEdit_80->setObjectName(QStringLiteral("lineEdit_80"));
        lineEdit_80->setGeometry(QRect(370, 370, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_80->sizePolicy().hasHeightForWidth());
        lineEdit_80->setSizePolicy(sizePolicy);
        lineEdit_80->setMinimumSize(QSize(40, 40));
        lineEdit_80->setMaximumSize(QSize(40, 40));
        lineEdit_80->setFont(font);
        lineEdit_80->setAlignment(Qt::AlignCenter);
        lineEdit_81 = new QLineEdit(centralWidget);
        lineEdit_81->setObjectName(QStringLiteral("lineEdit_81"));
        lineEdit_81->setGeometry(QRect(330, 290, 40, 40));
        sizePolicy.setHeightForWidth(lineEdit_81->sizePolicy().hasHeightForWidth());
        lineEdit_81->setSizePolicy(sizePolicy);
        lineEdit_81->setMinimumSize(QSize(40, 40));
        lineEdit_81->setMaximumSize(QSize(40, 40));
        lineEdit_81->setFont(font);
        lineEdit_81->setAlignment(Qt::AlignCenter);
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(450, 310, 75, 23));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(450, 350, 75, 23));
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(450, 390, 75, 23));
        LCDCurTimeCost = new QLCDNumber(centralWidget);
        LCDCurTimeCost->setObjectName(QStringLiteral("LCDCurTimeCost"));
        LCDCurTimeCost->setGeometry(QRect(450, 80, 91, 23));
        QFont font1;
        font1.setFamily(QStringLiteral("Arial"));
        font1.setPointSize(16);
        font1.setBold(true);
        font1.setItalic(false);
        font1.setWeight(75);
        LCDCurTimeCost->setFont(font1);
        LCDCurTimeCost->setDigitCount(10);
        curTimecost = new QLineEdit(centralWidget);
        curTimecost->setObjectName(QStringLiteral("curTimecost"));
        curTimecost->setGeometry(QRect(450, 50, 91, 20));
        curTimecost->setReadOnly(true);
        minTimeCost = new QLineEdit(centralWidget);
        minTimeCost->setObjectName(QStringLiteral("minTimeCost"));
        minTimeCost->setGeometry(QRect(450, 120, 91, 20));
        minTimeCost->setReadOnly(true);
        LCDMinTimeCost = new QLCDNumber(centralWidget);
        LCDMinTimeCost->setObjectName(QStringLiteral("LCDMinTimeCost"));
        LCDMinTimeCost->setGeometry(QRect(450, 150, 91, 23));
        QFont font2;
        font2.setFamily(QStringLiteral("Arial"));
        font2.setPointSize(16);
        font2.setBold(true);
        font2.setWeight(75);
        LCDMinTimeCost->setFont(font2);
        LCDMinTimeCost->setDigitCount(10);
        preGame = new QPushButton(centralWidget);
        preGame->setObjectName(QStringLiteral("preGame"));
        preGame->setGeometry(QRect(450, 190, 75, 23));
        nextGame = new QPushButton(centralWidget);
        nextGame->setObjectName(QStringLiteral("nextGame"));
        nextGame->setGeometry(QRect(450, 230, 75, 23));
        pushButton_6 = new QPushButton(centralWidget);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(550, 230, 75, 23));
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(550, 190, 75, 23));
        SudokuUIClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(SudokuUIClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 649, 23));
        SudokuUIClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(SudokuUIClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        SudokuUIClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(SudokuUIClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        SudokuUIClass->setStatusBar(statusBar);

        retranslateUi(SudokuUIClass);
        QObject::connect(lineEdit, SIGNAL(textChanged(QString)), SudokuUIClass, SLOT(testValuechange()));

        QMetaObject::connectSlotsByName(SudokuUIClass);
    } // setupUi

    void retranslateUi(QMainWindow *SudokuUIClass)
    {
        SudokuUIClass->setWindowTitle(QApplication::translate("SudokuUIClass", "SudokuUI", Q_NULLPTR));
        lineEdit->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_2->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_3->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_4->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_5->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_6->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_7->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_8->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_9->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_10->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_11->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_12->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_13->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_14->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_15->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_16->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_17->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_18->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_19->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_20->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_21->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_22->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_23->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_24->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_25->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_26->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_27->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_28->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_29->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_30->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_31->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_32->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_33->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_34->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_35->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_36->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_37->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_38->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_39->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_40->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_41->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_42->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_43->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_44->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_45->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_46->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_47->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_48->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_49->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_50->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_51->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_52->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_53->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_54->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_55->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_56->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_57->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_58->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_59->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_60->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_61->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_62->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_63->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_64->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_65->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_66->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_67->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_68->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_69->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_70->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_71->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_72->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_73->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_74->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_75->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_76->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_77->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_78->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_79->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_80->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        lineEdit_81->setText(QApplication::translate("SudokuUIClass", "1", Q_NULLPTR));
        pushButton->setText(QApplication::translate("SudokuUIClass", "\346\217\220\347\244\272", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("SudokuUIClass", "\345\256\214\346\210\220", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("SudokuUIClass", "\351\200\200\345\207\272", Q_NULLPTR));
        curTimecost->setText(QApplication::translate("SudokuUIClass", "\345\275\223\345\211\215\350\200\227\346\227\266\357\274\232", Q_NULLPTR));
        minTimeCost->setText(QApplication::translate("SudokuUIClass", "\346\234\200\344\275\263\347\272\252\345\275\225\357\274\232", Q_NULLPTR));
        preGame->setText(QApplication::translate("SudokuUIClass", "\344\270\212\344\270\200\345\205\263", Q_NULLPTR));
        nextGame->setText(QApplication::translate("SudokuUIClass", "\344\270\213\344\270\200\345\205\263", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("SudokuUIClass", "\345\206\215\347\216\251\344\270\200\347\273\204", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("SudokuUIClass", "\346\211\213\345\212\250\351\200\211\345\205\263", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class SudokuUIClass: public Ui_SudokuUIClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SUDOKUUI_H
